name: CI/CD Pipeline  # Corrected: file name should be defined under `name`

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # Specify the JDK distribution

    # Build the Java project using Maven
    - name: Build with Mavenname: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Nexus is local, so run on your Oracle Linux self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Run Tests
      run: mvn test

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.NEXUS_URL }}/devopstool-new:latest .

    - name: Login to Nexus Docker Registry
      run: echo ${{ secrets.NEXUS_PASSWORD }} | docker login ${{ secrets.NEXUS_URL }} -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

    - name: Push Docker Image to Nexus
      run: docker push ${{ secrets.NEXUS_URL }}/devopstool-new:latest

      run: mvn clean package

    # Run tests
    - name: Run Tests
      run: mvn test

    # Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/devopstool-new:latest .

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    # Push Docker image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devopstool-new:latest

      
