name: Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_ADMIN }}" | docker login -u "${{ secrets.DOCKER_sandy326 }}" --admin@#321-stdin

      - name: Build Docker image
        run: |
          docker build -t sandy326/devopstool:latest .

      - name: Push Docker image
        run: |
          docker push sandy326/devopstool:latest
