name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Change this to your desired JDK version
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Build Docker image
      run: |
        docker build -t sandy326/devopstool:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_sandy326 }}  # Make sure this matches your secret name
        password: ${{ secrets.DOCKER_admin@#321 }}  # Make sure this matches your secret name

    - name: Push Docker image
      run: |
        docker push sandy326/devopstool:latest
