name: Nexus CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-windows:
    name: Build and Test on Windows
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build project
        shell: cmd
        run: mvn clean package

      - name: Run unit tests
        shell: cmd
        run: mvn test

  cd-linux:
    name: Docker Build and Push on Linux
    runs-on: [self-hosted, Linux]
    needs: ci-windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.NEXUS_URL }}/devopstool-new:latest .

      - name: Login to Nexus Registry
        run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ secrets.NEXUS_URL }} -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

      - name: Push Image to Nexus
        run: docker push ${{ secrets.NEXUS_URL }}/devopstool-new:latest
